### PR TITLE
add missing partition name

### PR DESCRIPTION
**Pull request by Zlywilk**

### CODE REVIEW

**Comment by adamoutler** [comment]
I will not accept this. The 1 partition was contributed and reported working on another device.

**Comment by Zlywilk** [comment]
Zrzut ekranu z 2023-12-14 14-13-46
proof it works after run HA os import

**Comment by adamoutler** [comment]
But you're removing it for some other members. You need to add to, but not take away.

**Comment by Zlywilk** [comment]
I remove my wrong change xvda1 is boot partition xvda8 is data partition

**Comment by adamoutler** [comment]
Thank you.  I appreciate it.  

Boot will fail to mount and so the boot partition will be checked and fail before any attempt occurs.

**Pull request merged**
